### ISSUE TITLE
[Task] QR Codes

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/homebox#227]
## Description 

Homebox should support some basic QR Code generation features

## Feature Set

- [x] Create QR Codes for Items, Locations, and Tag pages #226
- [ ] Bulk export to PDF (or something) printable QR codes #274 

---

Please add ideas here, I'm not sure how to implement printable QR codes, or what the extent of QR codes should be.

**Comment by Serios** [comment]
Hi there I just recently found this wonderful project. Here some ideas what QR codes functionalities may be:

1. The obvious one - "See inside the box, without open it" - Slap a barcode on a box, then when scanning it HB loads a page with list of items that are assigned to that box/location. Also imagine if we have box/location of consumables, we know what's inside but don't remember what quantities we have, just scan the code and voila. I think this will be not so hard for implement, because most of the functionalities are already in place.

2. Use the QR as shortcut for quick creation of items/locations/boxes/labels - Just print a QR and put it on the desktop, wall etc. and then every time when it's scanned HB bring the form for adding items/locations/boxes/labels.

3. Again, obvious one - "Adding/removing item quantities quickly" - I think that QR is a bit overkill for this, since 99.5% of items nowadays have a simple barcode which can also be used as product code, since there's no possibility for two items with the same barcode available for purchase at the same time for a given country/market, that's the way international barcode system is designed to work, but nonetheless - if we generate QR, slap it on a item, then in HB we open a designated form for adding or removing quantities, every scan should load a item with a input field designated for quantity. A good usability case will be if the item is already loaded in the list, then just to increase/decrease the value in its input box with 1.

4. Use QR for quickly reorganizing/adding boxes to locations - If for example I have a box with items in the attic but at some point, decide to move the box to the garage or the basement space, scanning the location QR then the box QR should first deassign the box if is already assigned to this location or assign it to it, if not.


As for bulk export to PDF (or something) printable QR codes I think that [https://github.com/bpampuch/pdfmake](https://github.com/bpampuch/pdfmake) or [https://github.com/parallax/jsPDF](https://github.com/parallax/jsPDF) libraries will be of great use.
