### ISSUE TITLE
OpenID Connect Support

### ISSUE THREAD

**Issue by joeyame** [hay-kot/homebox#331]
### What is the problem you are trying to solve with this feature?

SSO for all my self-hosted web applications. Having to maintain multiple accounts across multiple web services is very cumbersome for me and for my family.

### What is the solution you are proposing?

An implementation / configuration option that allows user authentication and creation to be handled through a service like Keycloak, Nextcloud, or (in my case) Authentik

### What alternatives have you considered?

Alternative is just leaving it as it is.

### Additional context

I'm not against trying to take this on myself if the developers are burdened with other features.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [x] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by icsy7867** [comment]
Just jumping in here to add an opinion.  This is similar to https://github.com/hay-kot/homebox/issues/270

In my work environment, we use ADFS for SAML SSO, and I use Apache Mellon to add SAML auth to docker applications, and then pass the username (or other attributes) to the backend web app via a http header.  I like this method as it requires a fairly simple reverse proxy with minimal change to backend code.  

You could either remove auth, and have a single user, and use authelia or apache SAML (or whatever other tool) to handle this sort of auth.

Or pass the username to the backend via a header value, and create the new user if it doesn't exist.  Just suggesting, as this might be preferable to completely adding something like openid or SAML into your code, and you could leave it to the end user to setup via a proxy.

**Comment by joeyame** [comment]
Oh shoot yeah I guess I didn't look hard enough for a related. I will add as a counterpoint that the single user option, while suitable for SSO, is probably not appropriate for people who wish to serve multiple households / groups. I am trying to serve multiple family units so I do see multiple accounts as a necessity.

Just curious, are there any downsides to the SAML/OIDC method besides just a more complicated initial implementation? I've seen a few other projects that are hesitant to add it (vaultwarden is one), but haven't seen too much discussion why.

**Comment by icsy7867** [comment]
> Oh shoot yeah I guess I didn't look hard enough for a related. I will add as a counterpoint that the single user option, while suitable for SSO, is probably not appropriate for people who wish to serve multiple households / groups. I am trying to serve multiple family units so I do see multiple accounts as a necessity.
> 
> Just curious, are there any downsides to the SAML/OIDC method besides just a more complicated initial implementation? I've seen a few other projects that are hesitant to add it (vaultwarden is one), but haven't seen too much discussion why.

I can't speak for the project, but I'm my past experience these authentications can be quite complicated.  But most languages have libraries that you can use/implement.  But it is another thing to make sure it is updated.  Additionally, changing authentication mechanisms might have pretty large impact on the frontend, backend and documentation.

So, I would also like to see something added in this regard, but I don't think it is trivial, which is why I usually go the header route and let my common tools that I am familiar with do this in a proxy before the frontend.  But just my $0.02

**Comment by hay-kot** [comment]
I'm definitely not going to implement this. I'm open to a PR with the following caveats

- It can't break support for work described in https://github.com/hay-kot/homebox/issues/314
- Changes come with comprehensive integration tests with a authentication provider (via CI/Github Actions)
- Works with existing Group Model inside of Homebox
- Extensive documentation on what is required for users to set this up

this project and others are hesitant to add them because: 

- it's widely complicated and there's 100 different ways to do the same thing. Especially in the self-hosted community, there are many many many different authentication provider setups each with their varying edge cases. It's unlikely the implementation we chose will make everyone happy
- Implementations by PR almost always come half-baked without any tests. Which isn't a knock on the PR writer. It's difficult to make this addition sound and takes a lot of time. On my other project Mealie I've had probably 10 different PR's submitted to get this working in some capacity and fall off because the maintainer got it working for themselves, but didn't have time or wasn't willing to write tests, and make the implementation generic enough to fit multiple use cases
- These large PRs are often submitted by drive by committers. Which is to say that I don't have any indication that someone who submits this PR is willing to maintain it long term. Then it falls on the core maintainer to fix bugs and problems in a huge feature I don't even use.

**Comment by verybadsoldier** [comment]
What about supporting `Trusted Header SSO` (https://www.authelia.com/integration/trusted-header-sso/introduction/#response-headers) or a single user mode (as proposed in the linked issue)?

That Header SSO does not seem to be very complex and should be flexible enough for anyone interested in SSO to make use of it.

**Comment by hay-kot** [comment]
@verybadsoldier

> What about supporting Trusted Header SSO (https://www.authelia.com/integration/trusted-header-sso/introduction/#response-headers)

Seems like a pretty reasonable approach. Looks like it should be able to integrate with the group model. Thats. Probably where I would start.

**Comment by Coo-ops** [comment]
> * it's widely complicated and there's 100 different ways to do the same thing. Especially in the self-hosted community, there are many many many different authentication provider setups each with their varying edge cases. It's unlikely the implementation we chose will make everyone happy

Sorry but this is deeply short sighted.

OIDC is a standard, theres plenty of stuff that complies with the standards just fine.

Theres even whole libraries for providing OIDC for ones application.

**Comment by hay-kot** [comment]
@Coo-ops 

Sounds good. Looking forward to a PR that considers E2E Testing and Multi-tenancy. Should be easy since there's whole libraries that do it for you.

**Comment by GeorgeGedox** [comment]
You already got a PR trying to actually implement SSO and you ignored it and closed it. This feels like a punch to the face for people who are waiting for an SSO implementation in order to start using this.

**Comment by hay-kot** [comment]
If by ignored it you mean reviewed, provided feedback, and reviewed again, sure I guess I ignored it. I've laid out the requirements for what I'd need for a PR and so far no one has put in the effort to meet those requirements and provide a way to automatically test the integration. 

> This feels like a punch to the face for people who are waiting for an SSO implementation in order to start using this.

I'd also like to remind you that this software is free and open source. I am not paid to work on this. You feeling entitled to a feature does not mean anything. If you or anyone else would like to sponsor this work I'd be happy to provide a quote to implement it.

**Comment by verybadsoldier** [comment]
How can you say you didn't ignore it?
https://github.com/hay-kot/homebox/pull/345

I would also like to remind you that I had spend dozens of hours of my free and unpaid time to work on this project and out of nothing you stopped communication in that PR completely without giving any reasoning or explanation. Even after me and others explicitly asked for feedback several times in the months after, we were just ignored. This was after you said it was looking "really really good" and we are "super close". I was working to address all the points you raised in the PR. I still have no idea what the problem was, but sorry if it didn't meet your expectations.

Ditching that PR out of nothing without any explanation was super disrespectful.
Anyway, it was my decision to work on this project as a volunteer for free. My own bad luck when it turned out like this. Cannot recommend to anyone else, though.
