### ISSUE TITLE
Lack of barcode ID

### ISSUE THREAD

**Issue by edalcin** [hay-kot/homebox#534]
### What is the problem you are trying to solve with this feature?

I would like to associate barcode to the items of my inventory

### What is the solution you are proposing?

To create an attribute "barcode" for the inventory itens. Such as at Grocy application (https://grocy.info/). Could also be connected (API) to BarcodeBuddy (https://barcodebuddy-documentation.readthedocs.io/en/latest/usage.html)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Is this different than this issue?

- https://github.com/hay-kot/homebox/issues/191

**Comment by Doublemyst** [comment]
Is it possible to add the possibility to create "own" QR-Codes for boxes -> asset ID for locations, which are different from items.
At the moment the asset id's are given one by one for each item, and if I want to create a box, I need to create an item, and link all items in a parent item, which isn't really practical. On the other hand, I can create a location "box" link all items in this location, but when I want to print out a QR code with a name (like it is the case for items -> super handy), I need to do it manually. 
So if there were a way to handle "location" QR codes with names (for ease of search), similiar to items, but on a different counting scale (so I can just print a list of new boxes qr codes, without the hassle manually modify each asset id -> otherwise the boxes could have random asset ids, but the label generator has an asset start and end 000-001, 000-002, 000-003 and so on). Maybe all boxes would start with 700-001, or something similar).

**Comment by s-martin** [comment]
I would like to add my use case, don't think it's covered by the discussion here or in #191.

I would like to have a barcode scan function to scan the existing barcode of an item to use that as an identifier (e.g. to look it up easily later by scanning again).

Advantage from my point of view: I don't need to label an item with a QR code manually (i.e. create, print, etc), but rather use an existing barcode label.

From an UX point of view it would be helpful to add the possibility to use a barcode scanner to numeric identifier fields in addition to manually typing the identifier.

What do you think?

**Comment by greyduk** [comment]
Additionally, it could be a good way to pre-load some item data. Scan a UPC, API looks up what products that could be, homebox shows you the lost abs you click the best one. Manufacturer, description, etc all auto-completed.

**Comment by hay-kot** [comment]
I don't think these are really inline with what I intend for the project. If someone is developing a mobile app and needs some additional properties for working with barcodes, like is suggested, I'd be happy to work on something to enable that workflow but it would have to be handled outside of this app. 

Thanks!
