### ISSUE TITLE
Quantity on creating asset, sublabels, adding/removeing quantity

### ISSUE THREAD

**Issue by KnedlOF** [hay-kot/homebox#559]
### What is the problem you are trying to solve with this feature?

Hi I have some features that you could add:
1. when creating asset, there could be another field for quantity, with deafult of one. 
2. Sublabels, so for example you can have parent label electronics, and sublabel resistors...
3. some kind of button for adding and removing quantity, so you don't need calculator if there is bigger quantities

Issues:
-when creating/deleting location, I have to refresh a webpage in order to show/unshow in options when creating asset
-you can select the same location that you are setting as parent location, and then just dissapears forewer 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! Thanks for submitting an issue, in the feature please submit each piece individually if they are unrelated, otherwise they become difficult to track and harder for me to maintain. Thanks!

---

> 1. when creating asset, there could be another field for quantity, with deafult of one.

I'm pretty adamant on not adding any more fields to the create screen, so I won't be implementing this.

> 2. Sublabels, so for example you can have parent label electronics, and sublabel resistors...

I can kind of see why this would be useful, but I wouldn't use it and it's not trivial to implement so I won't be adding this. 

> 3. some kind of button for adding and removing quantity, so you don't need calculator if there is bigger quantities

This is already implemented in the latest beta

<img width="916" alt="image" src="https://github.com/hay-kot/homebox/assets/64056131/f110172f-0eb2-4fe0-a80d-e4827cc9dcfe">

> when creating/deleting location, I have to refresh a webpage in order to show/unshow in options when creating asset

This is fixed in the beta as well.

> you can select the same location that you are setting as parent location, and then just dissapears forewer

Can you please create a new issue using the bug template for this?
