### ISSUE TITLE
Label Generator is encoding the URL as a note, not a URL 

### ISSUE THREAD

**Issue by timdonovanuk** [hay-kot/homebox#564]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

https://homebox.fly.dev/reports/label-generator

### What is the issue you are experiencing?

On my phone (samsung s23) it tries to open the URL's on that page as https%3A%2F%2Ftest.com%2Fa%2F000-001 so clearly something is wrong with encoding here. 

### How can the maintainer reproduce the issue?

Go to the demo site, open https://homebox.fly.dev/reports/label-generator, scan a QR code.

### Deployment

Other

**Comment by avantegarde** [comment]
+1 I'm seeing this same behavior on the demo site along with my self hosted version. Both the label generator page as well as the qr codes being generated on individual item/asset pages are not encoded correctly.

**Comment by Smith3rman** [comment]
+1 I have the same problem on my side. The same problem happens in the Location QR-codes.

**Comment by bee-eater** [comment]
Same here

**Comment by WoosterInitiative** [comment]
I'm happy to take a look at the code, but my biggest problem is always finding where in the code the thing is generated, specifically, what module generates the QR code? If someone can point me to it, I'm happy to take a crack at a PR; else, I just don't have the time to dig through all of the code.

**Comment by porteusconf** [comment]
I see[ backend/app/api/handlers/v1/v1_ctrl_qrcode.go](https://github.com/hay-kot/homebox/blob/main/backend/app/api/handlers/v1/v1_ctrl_qrcode.go) imports go-qrcode from this git repo:
[https://github.com/yeqown/go-qrcode](https://github.com/yeqown/go-qrcode) which is active with only 5 issues at this time. So I may try to find out if the malformed URL is caused by go-qrcode or by homebox.

**Comment by jackwilsdon** [comment]
It appears that the issue is caused by the `/qrcode` URL generated by the frontend having double URL-encoded parameters:

https://homebox.fly.dev/api/v1/qrcode?data=https%253A%252F%252Fhomebox.fly.dev%252Fa%252F000-001

Decoding the data parameter once gives:

https://homebox.fly.dev/api/v1/qrcode?data=https%3A%2F%2Fhomebox.fly.dev%2Fa%2F000-001

Scanning the latter works fine. From a cursory glance at the frontend code, the issue appears to be in 2 places (label and item pages):

https://github.com/hay-kot/homebox/blob/0995478cc0da5eeaad5073e28a8d01d7a5cf3ba7/frontend/pages/reports/label-generator.vue#L181

https://github.com/hay-kot/homebox/blob/0995478cc0da5eeaad5073e28a8d01d7a5cf3ba7/frontend/components/global/PageQRCode.vue#L23

The data property probably shouldn't be URL-encoded here, as that is already handled in the `route` function:

https://github.com/hay-kot/homebox/blob/0995478cc0da5eeaad5073e28a8d01d7a5cf3ba7/frontend/lib/api/base/urls.ts#L22-L36

Using `url.searchParams` encodes the parameters automatically:

```javascript
const url = new URL("https://homebox.fly.dev/api/v1/qrcode");
url.searchParams.append("data", "https://homebox.fly.dev/a/000-001");
console.log(url.toString()); // https://homebox.fly.dev/api/v1/qrcode?data=https%3A%2F%2Fhomebox.fly.dev%2Fa%2F000-001
```

**Comment by Triple-Z** [comment]
same problem here, hope to see it solved in the next verion ❤️
