### ISSUE TITLE
Admin portal for user management

### ISSUE THREAD

**Issue by ados8** [hay-kot/homebox#687]
### What is the problem you are trying to solve with this feature?

I'm new to this application and really liking it.
As the tech member of my family I would like to host the application.
The application needs to support multiple users and I know it can but it has no control.

### What is the solution you are proposing?

Ability to block sign ups and have invite only.
Admin portal whereby the admin can create users and/invite people.
Users can then login under their account unique to them.
Admin can always reset their password, delete their account and ideally see a raw item count to see if the user has data.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I don't really have any intention of creating this because

1) Most of these things are already possible. You can have multiple users already with their own inventory or a shared inventory. You are required to let users sign-up then manually disable it with an ENV variable.
2) When you disable sign-ups you can still invite people to your shared group/inventory which I think is the most often use case here.
3) I'm planning to add password reset via a CLI inside the container and via email soon.

Given those points, I don't think it's worth the development time for this. It would require

1. New permission model for administrators
2. New way to create/modify permissions
3. New user management API 

I think that time is better spent improving the core user experience than this that can mostly already be done, if a little inconvenient. 

Given what I've said, is there anything else I should consider before closing this?

**Comment by Clem-** [comment]
Hi there, what about inviting an existing user to a shared inventory?
Thanks

**Comment by n00b12345** [comment]
@hay-kot could you consider having an API protocol to view all registered users? I think that would go a long way in the absence of an admin management system.
