### ISSUE TITLE
How to display the creation and modification time of an item?

### ISSUE THREAD

**Issue by myuanz** [hay-kot/homebox#712]
### What is the problem you are trying to solve with this feature?

I want to see the `createAt` and `updatedAt` fields on the item page.

### What is the solution you are proposing?

The two date filed show in `Details` table on `item` page.

### What alternatives have you considered?

Or put them to other table? 

### Additional context

I'm not sure if there's any deeper meaning to not displaying these two fields. I've checked the current issues and haven't seen any discussion about this, so I opened this issue.

Thank you for your excellent tool.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
That's a bug. They should be on the page. Feel free to open a PR if you'd like, otherwise I'll pick this up on the next round of bug fixes.

**Comment by hay-kot** [comment]
This was fixed in https://github.com/hay-kot/homebox/commit/c708b1759e507d87c83a22c0da7d31229c942155 but I forgot to mark it. Closes this now, will be in the next release or you can use nightly.

![CleanShot 2024-02-25 at 18 05 13@2x](https://github.com/hay-kot/homebox/assets/64056131/d66775f0-abbf-4215-a0ab-b4b1eeab98ac)

_obviously I'm still working on some timing issues..._
