### ISSUE TITLE
Bulk Edit Items Values/Remove

### ISSUE THREAD

**Issue by StoneCotton** [hay-kot/homebox#95]
### What is the problem you are trying to solve with this feature?

When messing around with the item import function, I found myself duplicating all items on import. This brought to my attention that as far as I can see, there is no way to bulk or mass change any of the items (for example delete, assign, etc.)

### What is the solution you are proposing?

A way to select multiple items and change various values that are assigned to them. These could be things like where they were purchased from, labels, locations, to things like mass deleting or archiving if that is implemented. What this would allow is in the scenario that you have dozens-hundreds of items that you need to alter (or another example is donate or move to a new location) these can be done on mass.

### What alternatives have you considered?

Manually having to select each item and change their values/existence in Homebox, which can create huge slowdowns when dealing with more than just a few items.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
> When messing around with the item import function, I found myself duplicating all items on import.

FYI, you can deduplicate imports by using the `Import Ref` column in the CSV. This is new in the latest release.

https://hay-kot.github.io/homebox/import-csv/#csv-reference

--- 

As for the main issue, I'm more inclined to rely on the CSV to do the bulk updating of items. Here's two features of the import that I think could fix solve this issue

1. Add a deleted (true/false) field and then that would ensure that the record was deleted from the database so we could remove items in bulk as needed
2. Update items with an Import Ref instead of just ignoring them. 

Then we don't have to built a complex custom bulk editor, but still get a lot of the main features you'd be looking for anyways.

What do you think?

**Comment by StoneCotton** [comment]
Oh that's great, I must have missed that part when compiling the CSV!

As for the solution you suggested, I agree that sounds like a much more streamlined approach from a development and usability standpoint. Having a check if the item information is different with Import Ref and a new field for if an item should be deleted handled through the import process would be great.

**Comment by hay-kot** [comment]
FYI #290 imports what we talked about here excluding mass delete items. Will look at that in a future patch.
