### ISSUE TITLE
URL field

### ISSUE THREAD

**Issue by dimatx** [hay-kot/homebox#96]
### What is the problem you are trying to solve with this feature?

I use paperless-ngx to store all of my manuals (among other docs)... Would be great to be able to link to other (self-) hosted systems that complement Homebox.

### What is the solution you are proposing?

Adding a URL field as a default  that produces a clickable link with option to prettify the link (e.g., 'Manual")

### What alternatives have you considered?

Custom fields would work, but you have to create one each time.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I don't know that I want to add a new field since I would think it would need to be a a list with options that sort of just align with custom fields. Two potential options that might work without changing too much

1. Extend Custom Fields to support the markdown link syntax `[Name](url)` and render those as clickable links
2. Auto-detect URLs in the custom fields and render them as buttons. (Maybe combined with the above?)

What do you think, would resolve this need?

**Comment by wazabees** [comment]
There is also a post about this in Discussions.
https://github.com/hay-kot/homebox/discussions/58

Using a custom field would support any kind of document management system. Making use of the [paperless-ngx API](https://paperless-ngx.readthedocs.io/en/latest/api.html) would also be an option.

**Comment by hay-kot** [comment]
Here's my rough implementation of what I described

![CleanShot 2022-10-19 at 16 21 44](https://user-images.githubusercontent.com/64056131/196828447-ede557e6-db77-4f9b-887a-261db2ef93c3.png)

![CleanShot 2022-10-19 at 16 22 17](https://user-images.githubusercontent.com/64056131/196828463-5a68075d-ef8f-41b2-b42f-52bd97ba5b3f.png)

**Comment by dimatx** [comment]
Sorry to chime in late, but yes, your proposed solution is great and would work well in my use case. Thanks!
